[tool.ruff]
line-length = 100
target-version = "py313"
exclude = [
	"filamentcontrol/",  # virtualenv directory
	"**/site-packages/",
	"__pycache__/",
]
[tool.ruff.lint]
select = ["E","F","W","I"]
ignore = ["E501","W191","I001","W293","E402"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.13"
strict = false
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
files = ["filamentbox/"]
exclude = [
    "filamentcontrol/",  # virtualenv
    "tests/",            # exclude tests initially
	"filamentbox.py",    # avoid module name clash with package
]


